language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run build
after_success:
- chmod a+x deploy.sh 
- "./deploy.sh"
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "mathias@feitzinger.org"